version: '4.19.x.{build}'

image:
  - Visual Studio 2017

configuration:
  - Debug
  - Release

platform:
  - x64
  - Win32
  - ARM64

test: off

deploy: off

matrix:
  fast_finish: true

before_build:
  - cmd: CALL update_rev.bat

for:
  - # MSVC Debug
    matrix:
      only:
        - configuration: Debug

    build_script:
      - cmd: CALL "build\VS2017\build.bat" Build %PLATFORM% Debug

  - # MSVC Release
    matrix:
      only:
        - configuration: Release

    build_script:
      - cmd: CALL "build\VS2017\build.bat" Build %PLATFORM% Release
      - cmd: CALL "build\make_zip.bat" MSVC %PLATFORM% Release

    artifacts:
      - path: 'build\Notepad2*.zip'
        name: Notepad2
